version: 2
updates:
  - package-ecosystem: maven
    directory: quarkus-spring-todo-app
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: quarkus-spring-todo-app
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: quarkus-todo-app
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: quarkus-todo-app
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: spring-todo-app
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: spring-todo-app
    schedule:
      interval: daily