
start-infra:
    echo "Starting database..."
    podman run --name database --ulimit memlock=-1:-1 -d -it --rm=true \
        -e POSTGRES_USER=quarkus_test \
        -e POSTGRES_PASSWORD=quarkus_test \
        -e POSTGRES_DB=quarkus_test \
        -p 5432:5432 postgres:15-bullseye

stop-infra:
    podman stop database
