spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quarkus_test
    username: quarkus_test
    password: quarkus_test
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
